extends: airbnb/legacy # TODO: add es6 compiler and move away from legacy.
plugins:
  - react
rules:
  # TODO: remove all those exceptions as we go.
  comma-style: 0
  no-unused-vars: 0
  semi: 0
  no-nested-ternary: 0
  camelcase: 0
  no-shadow: 0
  vars-on-top: 0
  dot-notation: 0
  eqeqeq: 0
  func-names: 0
  one-var: 0
  no-undef: 0
  quotes: 0
  block-scoped-var: 0
  no-use-before-define: 0
  max-len: 0
  quote-props: 0
  no-unused-expressions: 0
  comma-dangle: 0
  no-redeclare: 0
  new-cap: 0
  guard-for-in: 0
  object-curly-spacing: 0
  no-param-reassign: 0
  consistent-return: 0
  no-else-return: 0